//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWorkWinform.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeWorkWinform.Lang.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add Furniture.
        /// </summary>
        internal static string addFurniture {
            get {
                return ResourceManager.GetString("addFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buttonWall.
        /// </summary>
        internal static string buttonWall {
            get {
                return ResourceManager.GetString("buttonWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee-table.
        /// </summary>
        internal static string coffeeTable {
            get {
                return ResourceManager.GetString("coffeeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to createFurniture.
        /// </summary>
        internal static string createFurniture {
            get {
                return ResourceManager.GetString("createFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double-Bed.
        /// </summary>
        internal static string doubleBed {
            get {
                return ResourceManager.GetString("doubleBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room designer.
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageToolStripMenuItem {
            get {
                return ResourceManager.GetString("languageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load.
        /// </summary>
        internal static string loadFail {
            get {
                return ResourceManager.GetString("loadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint loaded succesfully.
        /// </summary>
        internal static string loadSucc {
            get {
                return ResourceManager.GetString("loadSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Blueprint.
        /// </summary>
        internal static string newBlueprintToolStripMenuItem {
            get {
                return ResourceManager.GetString("newBlueprintToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save fail.
        /// </summary>
        internal static string saveFail {
            get {
                return ResourceManager.GetString("saveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint saved succesfully.
        /// </summary>
        internal static string saveSucc {
            get {
                return ResourceManager.GetString("saveSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sofa.
        /// </summary>
        internal static string sofa {
            get {
                return ResourceManager.GetString("sofa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Blueprint.
        /// </summary>
        internal static string String1openBlueprintToolStripMenuItem {
            get {
                return ResourceManager.GetString("String1openBlueprintToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Blueprint.
        /// </summary>
        internal static string String1saveBlueprintToolStripMenuItem {
            get {
                return ResourceManager.GetString("String1saveBlueprintToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table.
        /// </summary>
        internal static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
    }
}
